# NPS_Airbnb

## Importing numpy

In [1]:
import numpy as np

## NPS

In [38]:
score=np.loadtxt("Survey.txt")
score

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [39]:
score.size

1167

In [47]:
Total_population=score.size
Total_population

1167

In [40]:
score.max()

10.0

In [41]:
score.min()

1.0

#### Detractors

In [70]:
score<=6

array([False, False,  True, ...,  True, False, False])

In [71]:
score[score<=6]

array([5., 4., 4., 5., 1., 5., 5., 1., 4., 5., 4., 4., 4., 5., 1., 4., 1.,
       4., 1., 5., 5., 1., 1., 4., 1., 5., 4., 1., 1., 4., 1., 5., 1., 4.,
       4., 1., 1., 1., 1., 1., 1., 1., 4., 1., 1., 5., 5., 5., 4., 4., 1.,
       4., 1., 4., 1., 5., 1., 1., 5., 4., 4., 4., 4., 1., 4., 5., 4., 4.,
       1., 1., 5., 5., 1., 5., 1., 5., 5., 4., 5., 4., 1., 1., 1., 1., 4.,
       1., 4., 4., 5., 4., 1., 1., 1., 1., 5., 4., 5., 5., 4., 1., 5., 1.,
       4., 4., 1., 1., 1., 4., 4., 5., 5., 4., 5., 5., 5., 1., 4., 1., 5.,
       5., 1., 5., 1., 1., 5., 5., 4., 4., 1., 4., 4., 4., 1., 1., 4., 4.,
       4., 5., 5., 1., 1., 4., 1., 4., 1., 4., 1., 4., 1., 4., 1., 5., 4.,
       4., 5., 1., 4., 5., 5., 5., 1., 5., 4., 1., 1., 5., 5., 5., 4., 5.,
       4., 4., 1., 4., 4., 4., 4., 5., 1., 5., 5., 1., 4., 4., 5., 1., 1.,
       4., 5., 5., 5., 1., 4., 5., 5., 4., 1., 5., 5., 5., 1., 1., 5., 5.,
       1., 1., 1., 4., 5., 5., 4., 4., 4., 5., 1., 4., 1., 4., 5., 4., 5.,
       5., 1., 5., 1., 5.

In [46]:
num_detractors=score[score<=6].size
num_detractors

332

#### Passive = score=7 or 8

In [ ]:
(score >= 7) & (score <= 8)

In [51]:
score[(score >= 7) & (score <= 8)]

array([7., 7., 7., 7., 8., 8., 8., 7., 7., 7., 8., 8., 7., 8., 8., 8., 8.,
       7., 7., 7., 8., 7., 7., 7., 8., 7., 8., 8., 7., 8., 8., 8., 7., 8.,
       7., 8., 8., 7., 8., 7., 8., 7., 7., 8., 8., 8., 7., 7., 8., 8., 8.,
       7., 7., 7., 8., 7., 7., 8., 7., 7., 7., 8., 7., 7., 8., 8., 8., 7.,
       7., 7., 7., 7., 8., 8., 7., 8., 7., 8., 8., 7., 8., 7., 7., 8., 7.,
       7., 7., 7., 7., 8., 8., 7., 7., 8., 8., 8., 8., 8., 7., 7., 7., 8.,
       7., 8., 8., 7., 7., 8., 8., 7., 7., 8., 7., 7., 8., 8., 8., 7., 7.,
       8., 8., 8., 8., 7., 7., 7., 8., 7., 7., 7., 7., 8., 7., 8., 7., 7.,
       7., 8., 8., 8., 7., 8., 8., 8., 8., 7., 8., 7., 7., 7., 7., 7., 8.,
       7., 7., 7., 7., 8., 7., 8., 8., 7., 7., 8., 8., 7., 8., 8., 7., 7.,
       7., 8., 8., 7., 7., 8., 7., 7., 7., 8., 7., 7., 7., 8., 7., 7., 7.,
       7., 7., 8., 8., 7., 8., 7., 7., 7., 8., 8., 8., 8., 8., 7., 8., 7.,
       7., 8., 7., 7., 8., 7., 8., 8., 7., 7., 8., 8., 8., 7., 8., 8., 7.,
       7., 7., 7., 7., 8.

In [56]:
num_passive=score[(score >= 7) & (score <= 8)].size
num_passive

226

#### Promoters = ( score=9 or 10)

In [57]:
score >= 9

array([False,  True, False, ..., False,  True,  True])

In [59]:
score[score >= 9]

array([10.,  9.,  9.,  9.,  9.,  9., 10.,  9.,  9., 10.,  9.,  9.,  9.,
        9.,  9.,  9.,  9., 10., 10.,  9., 10.,  9., 10.,  9.,  9., 10.,
       10.,  9., 10.,  9., 10., 10., 10.,  9.,  9., 10., 10., 10.,  9.,
       10.,  9., 10.,  9.,  9.,  9., 10.,  9.,  9.,  9.,  9.,  9.,  9.,
       10.,  9.,  9.,  9., 10.,  9., 10.,  9.,  9.,  9.,  9.,  9., 10.,
       10.,  9., 10.,  9.,  9., 10.,  9.,  9., 10.,  9.,  9.,  9.,  9.,
        9.,  9.,  9.,  9.,  9.,  9.,  9., 10.,  9.,  9.,  9.,  9.,  9.,
        9.,  9.,  9., 10.,  9.,  9.,  9.,  9.,  9., 10., 10.,  9., 10.,
       10., 10., 10.,  9., 10.,  9.,  9.,  9.,  9.,  9.,  9.,  9., 10.,
        9., 10.,  9., 10.,  9., 10., 10., 10.,  9.,  9., 10., 10.,  9.,
        9.,  9.,  9., 10.,  9.,  9.,  9.,  9., 10., 10.,  9.,  9.,  9.,
       10.,  9.,  9.,  9.,  9.,  9., 10.,  9.,  9.,  9., 10.,  9., 10.,
       10.,  9.,  9.,  9.,  9., 10.,  9., 10.,  9.,  9.,  9.,  9., 10.,
        9., 10.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9

In [61]:
Num_Promoters=score[score >= 9].size
Num_Promoters

609

In [62]:
num_detractors+num_passive+Num_Promoters

1167

In [65]:
percentage_promoters=np.round(Num_Promoters/Total_population*100,2)
percentage_promoters

52.19

In [66]:
percentage_detractors=np.round(num_detractors/Total_population*100,2)
percentage_detractors

28.45

In [67]:
percentage_passive=np.round(num_passive/Total_population*100,2)
percentage_passive

19.37

In [69]:
NPS=percentage_promoters-percentage_detractors
NPS

23.74